# (PART) Version control and R Markdown  {-} 

```{r include = FALSE}
source("common.R")
```

# Overview {-}

Although this part now links out to external resources, if you're working through this material on your own, let this be a nudge to pause around here and think about your workflow. I give you permission to spend some time and energy sorting this out! It can be as or more important than learning a new R function or package. The experts don't talk about this much, because they've already got a workflow and it's something they do almost without thinking.

Working through subsequent material in R Markdown documents, possibly using Git and GitHub to track and share your progress, is a great idea and will leave you more prepared for your future data analysis projects. Typing individual lines of R code is but a small part of data analysis and it pays off to think holistically about your workflow.

# Git, GitHub, and RStudio {#version-control}

<!--Original content: https://stat545.com/git08_claim-stat545-repo.html-->

At this point in STAT 545, all students receive their own STAT 545 GitHub repository that they will use to develop their course work throughout the rest of the course.

This has two purposes:

  * It is helpful for course mechanics, e.g. homework submission and grading,
    peer review.
  * Learning to use Git and GitHub, with R and RStudio, is a legitimate
    pedagogical goal.
    
Our instructions around installation, setup, and early Git usage eventually grew so extensive that we created a dedicated website. This content can now be found here:

<https://happygitwithr.com>

# R Markdown {#r-markdown}

<!--Original content: https://stat545.com/block007_first-use-rmarkdown.html-->

STAT 545 course work is generally submitted in the form of R Markdown documents. Students submit an `.Rmd` file, which they have executed or rendered to a `.md` markdown file. R Markdown is a very accessible way to create computational documents that combine prose and tables and figures produced by R code.

An introductory R Markdown workflow, including how it intersects with Git, GitHub, and RStudio, is now maintained within the Happy Git site:

[Test drive R Markdown](https://happygitwithr.com/rmd-test-drive.html)
